Wai-Technologies/raaghu-react

raaghu-elements/src/components/rds-alert/index.ts
raaghu-elements/src/components/rds-alert/rds-alert.css
raaghu-elements/src/components/rds-alert/rds-alert.stories.tsx
raaghu-elements/src/components/rds-alert/rds-alert.tsx
raaghu-elements/src/components/rds-avatar/index.ts
raaghu-elements/src/components/rds-avatar/rds-avatar.css
raaghu-elements/src/components/rds-avatar/rds-avatar.stories.tsx
raaghu-elements/src/components/rds-avatar/rds-avatar.tsx
raaghu-elements/src/components/rds-input/index.ts

Added Alert and Avatar elements to raaghu-elements.
Fixes #14   #15
Storybook

Added Alert and Avatar elements

---

raaghu-elements/rollup.config.js
raaghu-elements/src/rds-dropdown/rds-dropdown.stories.tsx
raaghu-elements/src/rds-dropdown/rds-dropdown.tsx

>
Fixes #32 
- Through Storybook

Added listItems feature to Dropdown element

---

raaghu-elements/src/rds-dropdown-list/index.ts
raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx

Added Dropdown List element

---

raaghu-elements/rollup.config.js
raaghu-elements/src/index.ts
raaghu-elements/src/rds-carousel/index.ts
raaghu-elements/src/rds-carousel/rds-carousel.scss
raaghu-elements/src/rds-carousel/rds-carousel.stories.tsx
raaghu-elements/src/rds-carousel/rds-carousel.tsx

Added Carousel element in raaghu-elements.
Fixes #61 

Added Carousel element

---

raaghu-elements/src/index.ts
raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
raaghu-elements/src/rds-input-group/index.ts
raaghu-elements/src/rds-input-group/rds-input-group.stories.tsx
raaghu-elements/src/rds-input-group/rds-input-group.tsx

Fixes #72 
> Made Input Group component

Made RdsInputGroup

---

raaghu-elements/src/rds-button/rds-button.scss
raaghu-elements/src/rds-button/rds-button.tsx
raaghu-elements/src/rds-input-group/rds-input-group.scss
raaghu-elements/src/rds-input-group/rds-input-group.stories.tsx
raaghu-elements/src/rds-input-group/rds-input-group.tsx
raaghu-elements/src/rds-input/rds-input.scss
raaghu-elements/src/rds-input/rds-input.tsx

1. Replaced default HTML elements 'input' and 'button' with RdsInput and RdsButton.
2. Made required changes in RdsInput and RdsButton
Fixes #72

Enhanced RdsInputGroup

---

raaghu-elements/src/index.ts
raaghu-elements/src/rds-chart-area/index.ts
raaghu-elements/src/rds-chart-area/rds-chart-area.scss
raaghu-elements/src/rds-chart-area/rds-chart-area.stories.tsx
raaghu-elements/src/rds-chart-area/rds-chart-area.tsx

Added Area Chart in raaghu elements.
Fixes #87 

Added Area Chart

---

raaghu-elements/src/index.ts
raaghu-elements/src/rds-illustration/index.ts
raaghu-elements/src/rds-like-dislike/index.ts
raaghu-elements/src/rds-spinner-re/index.ts
raaghu-elements/src/rds-text-area/index.ts

Added Index.ts file in elements

Added Index.ts file in elements

---

raaghu-elements/package.json
raaghu-elements/src/rds-datepicker/rds-datepicker.scss
raaghu-elements/src/rds-datepicker/rds-datepicker.stories.tsx
raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
raaghu-elements/src/rds-input-group/rds-input-group.stories.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.stories.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.tsx

Made default element for Date-picker 
Fixes #53 
- [] I have commented my code, particularly in hard-to-understand areas

Made RdsDatePicker - default

---

raaghu-elements/src/rds-big-number/rds-big-number.stories.tsx
raaghu-elements/src/rds-big-number/rds-big-number.tsx
raaghu-elements/src/rds-like-dislike/rds-like-dislike.tsx
raaghu-elements/src/rds-notification/rds-notification.scss
raaghu-elements/src/rds-notification/rds-notification.stories.tsx
raaghu-elements/src/rds-notification/rds-notification.tsx
raaghu-elements/src/rds-pagination/rds-pagination.tsx
raaghu-elements/src/rds-size/rds-size.stories.tsx
raaghu-elements/src/rds-stat/rds-stat.stories.tsx
raaghu-elements/src/rds-stat/rds-stat.tsx
raaghu-elements/src/rds-widget/rds-widget.stories.tsx
raaghu-elements/src/rds-widget/rds-widget.tsx

Added Notification element in raaghu-element
Fixes #132 

Added Notification element

---

raaghu-elements/src/rds-datepicker/rds-datepicker.scss
raaghu-elements/src/rds-datepicker/rds-datepicker.tsx

Fixes #53 
Added new advanced functionalities for date picker which needed to be improved later.
- [] I have commented my code, particularly in hard-to-understand areas

Made RdsDatePicker - advanced. (Need to add more functionality)

---

raaghu-elements/src/rds-modal/index.ts
raaghu-elements/src/rds-modal/rds-modal.scss
raaghu-elements/src/rds-modal/rds-modal.stories.tsx
raaghu-elements/src/rds-modal/rds-modal.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
raaghu-elements/src/rds-popover/index.ts
raaghu-elements/src/rds-popover/rds-popover.scss
raaghu-elements/src/rds-popover/rds-popover.stories.tsx
raaghu-elements/src/rds-popover/rds-popover.tsx

Added Modal Element and worked on popover element. Improved Offcanvas.
Fixes #147 
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings

Added Modal element.

---

raaghu-elements/src/rds-datepicker/rds-datepicker.stories.tsx
raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.scss
raaghu-elements/src/rds-navtabs/rds-navtabs.stories.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.tsx

Made RdsDatePicker advanced and made changes to RdsNavtabs

---

raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.scss
raaghu-elements/src/rds-navtabs/rds-navtabs.stories.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.tsx

Made RdsNavtabs

---

raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.stories.tsx
raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.tsx
raaghu-elements/src/rds-checkbox-parent-child/rds-checkbox-parent-child.scss
raaghu-elements/src/rds-checkbox-parent-child/rds-checkbox-parent-child.stories.tsx
raaghu-elements/src/rds-checkbox-parent-child/rds-checkbox-parent-child.tsx
raaghu-elements/src/rds-checkbox/rds-checkbox.stories.tsx
raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
raaghu-elements/src/rds-pagination/rds-pagination.stories.tsx
raaghu-elements/src/rds-pagination/rds-pagination.tsx

Added Checkbox Group and made some changes in pagination.
Fixes #159

Added Checkbox Group and made some changes in pagination

---

raaghu-mfe/rds_components/src/organization-tree/rds-comp-organization-tree.tsx

Enhancement in Organization Tree Component

---

raaghu-elements/src/rds-pagination/rds-pagination.tsx
raaghu-mfe/rds_components/src/rds-comp-data-table/rds-comp-data-table.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-mfe/rds_components/src/rds-comp-edition-list/rds-comp-edition-list.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-edition-list/rds-comp-edition-list.tsx

Enhancement in RdsCompDataTable and Made RdsCompEditionList

---

raaghu-elements/src/rds-banner/rds-banner.scss
raaghu-elements/src/rds-banner/rds-banner.stories.tsx
raaghu-elements/src/rds-banner/rds-banner.tsx

- Made changes in styles
- Added 'with_icon' and 'with_close_button' variants
Fixes #263 

Enhancement in RdsBanner

---

raaghu-elements/src/rds-feature-list/rds-feature-list.scss
raaghu-elements/src/rds-feature-list/rds-feature-list.stories.tsx
raaghu-elements/src/rds-feature-list/rds-feature-list.tsx

> Required changes in style
> Added feature for multiple column list
Fixes #265

Enhancement in RdsFeatureList

---

raaghu-elements/src/rds-rating/rds-rating.stories.tsx
raaghu-elements/src/rds-rating/rds-rating.tsx

Enhanced RdsRating element

---

raaghu-elements/src/rds-app-detail/rds-app-detail.stories.tsx
raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
raaghu-elements/src/rds-big-number/rds-big-number.tsx
raaghu-elements/src/rds-modal/rds-modal.tsx
raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
raaghu-mfe/rds_components/src/App.tsx
raaghu-mfe/rds_components/src/rds-comp-address-input/rds-comp-address-input.tsx
raaghu-mfe/rds_components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
raaghu-mfe/rds_components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
raaghu-mfe/rds_components/src/rds-comp-app-detail/rds-comp-app-detail.tsx
raaghu-mfe/rds_components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
raaghu-mfe/rds_components/src/rds-comp-card-detail-list/rds-comp-card-detail-list.stoies.tsx
raaghu-mfe/rds_components/src/rds-comp-client-basic/rds-comp-client-basic.tsx
raaghu-mfe/rds_components/src/rds-comp-email-settings-new/rds-comp-email-settings-new.tsx
raaghu-mfe/rds_components/src/rds-comp-email/rds-comp-email.tsx
raaghu-mfe/rds_components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
raaghu-mfe/rds_components/src/rds-comp-integration/rds-comp-integration.tsx
raaghu-mfe/rds_components/src/rds-comp-login/rds-comp-login.tsx
raaghu-mfe/rds_components/src/rds-comp-security/rds-comp-security.tsx
raaghu-mfe/rds_components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
raaghu-mfe/rds_components/src/rds-comp-tenant-list/rds-comp-tenant-list.tsx
raaghu-mfe/rds_components/src/rds-comp-tenant-management/rds-comp-tenant-management.tsx
raaghu-mfe/rds_components/src/rds-comp-testimonials/rds-comp-testimonials.tsx
raaghu-mfe/rds_components/src/rds-comp-website-log/rds-comp-website-log.tsx
raaghu-mfe/rds_components/webpack.config.js
raaghu-mfe/rds_pages/host/src/App.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/login/src/App.tsx
raaghu-mfe/rds_pages/login/src/Login/Login.tsx
raaghu-mfe/rds_pages/login/webpack.config.js

Changes in Components to solve the error

---

raaghu-elements/src/rds-accordion/rds-accordion.scss
raaghu-elements/src/rds-file-uploader/index.ts
raaghu-elements/src/rds-file-uploader/rds-file-uploader.scss
raaghu-elements/src/rds-file-uploader/rds-file-uploader.stories.tsx
raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx

added file-uploader
Fixes #69 

added file-uploader

---

raaghu-elements/src/rds-icon/rds-icon.tsx
raaghu-elements/src/rds-pagination/rds-pagination.tsx
raaghu-elements/src/rds-tag/rds-tag.scss
raaghu-elements/src/rds-tag/rds-tag.stories.tsx
raaghu-elements/src/rds-tag/rds-tag.tsx

Added tag element and made some changes in icon
Added tag element and made some changes in icon
Fixes #312 

 Added tag element and made some changes in icon

---

raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.scss
raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx

Made and added one more type of RdsBreadcrumb

---

raaghu-elements/src/rds-file-uploader/rds-file-uploader.scss
raaghu-elements/src/rds-file-uploader/rds-file-uploader.stories.tsx
raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx

Completely built File-uploader with all functionality and changeable parameter
Fixes #69 
Completely built file-uploader

completely built file-uploader

---

raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
raaghu-elements/src/rds-accordion/rds-accordion.tsx

>
Minor changes in accordion element 
Fixes #279 

minor changes in Accordion

---

.github/workflows/development_raaghumfestageui.yml
raaghu-mfe/rds_pages/host/.env
raaghu-mfe/rds_pages/login/.env

changes in host for deployment

---

raaghu-mfe/rds_pages/host/.env

Update .env for deploy

---

raaghu-elements/src/rds-accordion/rds-accordion.scss
raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
raaghu-elements/src/rds-accordion/rds-accordion.tsx
raaghu-mfe/rds_components/src/rds-comp-claim/rds-comp-claim.scss
raaghu-mfe/rds_components/src/rds-comp-claim/rds-comp-claim.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-claim/rds-comp-claim.tsx

made flush and always open accordion

---

raaghu-mfe/rds_components/src/rds-comp-claim/rds-comp-claim.scss
raaghu-mfe/rds_components/src/rds-comp-claim/rds-comp-claim.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-claim/rds-comp-claim.tsx

Create Claim component completely
Fixes #390 

Create Claim component completely

---

raaghu-elements/src/rds-review-category/rds-review-category.stories.tsx
raaghu-elements/src/rds-review-category/rds-review-category.tsx
raaghu-mfe/rds_components/src/rds-comp-feeds/rds-comp-feeds.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-feeds/rds-comp-feeds.tsx
raaghu-mfe/rds_components/src/rds-comp-reviews/rds-comp-reviews.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-reviews/rds-comp-reviews.tsx
raaghu-mfe/rds_components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.tsx

1. Created Tenant Dashboard Component
2. Created 2 types of Reviews Component
3. Improved Feeds Component
4. Improved Review Category Element
Fixes #411 #413 #416 
- Test A
- Test B

Created Tenant Dashboard and 2 types of Reviews Component, Improved Feeds, Review Category element

---

raaghu-mfe/rds_components/src/rds-comp-data-table/rds-comp-data-table.scss
raaghu-mfe/rds_components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-mfe/rds_components/src/rds-comp-login-attempts/rds-comp-login-attempts.scss
raaghu-mfe/rds_components/src/rds-comp-login-attempts/rds-comp-login-attempts.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-login-attempts/rds-comp-login-attempts.tsx

create login attempts
Fixes #420 
create login attempts

create login attempts

---

raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
raaghu-mfe/package.json
raaghu-mfe/rds_components/src/rds-comp-calendar/rds-comp-calendar.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-calendar/rds-comp-calendar.tsx
raaghu-mfe/rds_components/src/rds-comp-data-table/rds-comp-data-table.tsx

Create calendar component
Fixes #397

Create calendar component

---

raaghu-mfe/rds_components/src/rds-comp-login-attempts/rds-comp-login-attempts.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-notification-settings/rds-comp-notification-settings.scss
raaghu-mfe/rds_components/src/rds-comp-notification-settings/rds-comp-notification-settings.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-notification-settings/rds-comp-notification-settings.tsx

create Notification settings
Fixes #434 

create Notification settings

---

raaghu-mfe/rds_components/src/rds-comp-login-attempts/rds-comp-login-attempts.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-login-attempts/rds-comp-login-attempts.tsx

Improved Login attempts by adding all option in select menu
Fixes #420 

Improved Login attempts

---

.github/workflows/development_raaghumfestageui.yml
raaghu-mfe/rds_pages/port-config.ts
raaghu-mfe/utils/build.js

updated build.js and yml file for deployment 

---

raaghu-elements/src/rds-notification/rds-notification.tsx

Updated Notification Element according to wireframe
Fixes #437 

 Updated Notification Element.

---

package.json
raaghu-mfe/rds_pages/dashboard/webpack.config.js
raaghu-mfe/rds_pages/forgotpassword/webpack.config.js
raaghu-mfe/rds_pages/host/webpack.config.js
raaghu-mfe/rds_pages/login/webpack.config.js
raaghu-mfe/rds_pages/maintainance/webpack.config.js
raaghu-mfe/rds_pages/organization-units/webpack.config.js
raaghu-mfe/rds_pages/settings/webpack.config.js

Updated Webpack.config files
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings

Updated Webpack.config files.

---

raaghu-elements/src/rds-notification/rds-notification.stories.tsx

Removed unread props from notification
Fixes #437 

Removed unread props from notification

---

raaghu-mfe/rds_components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-mfe/rds_pages/host/webpack.config.js

Update webpack.config and top nav file.
Type of change
Checklist:
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings

Update webpack.config and top nav file.

---

raaghu-elements/src/rds-navtabs/rds-navtabs.scss
raaghu-elements/src/rds-navtabs/rds-navtabs.stories.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.tsx

Updated Navtabs Element according to visual Setting Component.
Fixes #459 

Updated Navtabs Element according to visual Setting Component

---

raaghu-elements/src/rds-modal/rds-modal.stories.tsx
raaghu-elements/src/rds-modal/rds-modal.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
raaghu-mfe/rds_components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
raaghu-mfe/rds_components/src/rds-comp-organization-tree-new/rds-comp-organization-tree-new.scss
raaghu-mfe/rds_components/src/rds-comp-organization-tree-new/rds-comp-organization-tree-new.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-organization-tree-new/rds-comp-organization-tree-new.tsx
raaghu-mfe/rds_components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx

Create Organization tree
Fixes #168 

Create Organization tree

---

raaghu-mfe/rds_components/src/rds-comp-login-attempts/rds-comp-login-attempts.stories.tsx
raaghu-mfe/rds_components/src/rds-comp-login-attempts/rds-comp-login-attempts.tsx
raaghu-mfe/rds_components/src/rds-comp-notification-settings/rds-comp-notification-settings.tsx

Minor changes in Login attempts
Fixes #443 

Minor changes in Login attempts

---

.github/workflows/development_storybookreact.yml
package.json

update package.json and yml file of storybook to show the images.

---

raaghu-elements/package.json
raaghu-elements/rollup.config.js

Reduced npm package to 19mb
Fixes #497 

Reduced npm package to 19mb

---

raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx

Made imp changes to Alert-popup component
Fixes #182  

Made imp changes to Alert-popup component

---

raaghu-elements/src/rds-modal/rds-modal.stories.tsx
raaghu-elements/src/rds-modal/rds-modal.tsx

Made imp changes to Modal
Fixes #147 

Made imp changes to Modal

---

raaghu-components/src/rds-comp-cache/rds-comp-cache.stories.tsx
raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx

Added delete functionality in cache component

---

raaghu-mfe/utils/build.js

Enhancement in build.js file 

---

raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx

added dynamic Id in  Off-canvas
Fixes #122 

added dynamic Id in  Off-canvas

---

raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
raaghu-components/src/rds-comp-organization-tree-new/rds-comp-organization-tree-new.stories.tsx
raaghu-components/src/rds-comp-organization-tree-new/rds-comp-organization-tree-new.tsx

Added edit functionality to organization tree
Fixes #168 

Added edit functionality to organization tree

---

raaghu-components/src/rds-comp-organization-tree-new/rds-comp-organization-tree-new.tsx

>
Update rds-comp-organization-tree and added delete functionality
Fixes #168 

Update rds-comp-organization-tree and added delete functionality

---

raaghu-mfe/rds_pages/host/src/App.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx

Updated i18n (for Language change) in Host page.
Fixes #507 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings

Updated i18n in host page.

---

raaghu-components/src/index.ts
raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.stories.tsx
raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.tsx
raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
raaghu-mfe/rds_pages/rds-page-tenant/src/App.tsx
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.stories.tsx
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx

1. Created Tenant Page
2. Added submit functionality in tenant information, tenant settings component
Fixes #518

Create Tenant Page and Improved Tenant Information, Settings Component

---

raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
raaghu-elements/src/rds-side-nav-new/rds-side-nav-main.tsx
raaghu-elements/src/rds-side-nav-new/rds-side-nav-new.scss
raaghu-elements/src/rds-side-nav-new/rds-side-nav-new.stories.tsx
raaghu-elements/src/rds-side-nav-new/rds-side-nav-new.tsx

improved side navigation.
Fixes #81 
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings

Improved side-nav

---

raaghu-components/src/index.ts
raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx
raaghu-components/src/rds-comp-data-table/rds-comp-data-table.stories.tsx
raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-elements/src/rds-illustration/rds-illustration.tsx

Added Edit Action in Data Table component and made some changes in illustration element and removed comments from cache component
Fixes #534 #427 

 Added Edit Action in Data Table component 

---

raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx

Updated Webhook subscription component.
Fixes #536 

Updated Webhook subscription component

---

raaghu-elements/src/rds-navtabs/rds-navtabs.scss
raaghu-elements/src/rds-navtabs/rds-navtabs.tsx

Removed hardcode color for navtabs in RdsNavtabs element.
Fixes #544 

Removed hardcode color for navtabs in RdsNavtabs element.

---

raaghu-components/src/rds-comp-edition-list/rds-comp-edition-list.tsx
raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.scss

Fixed bug in tenant list and edition list component .
Fixes #547

Fixed bug in tenant list and edition list component .

---

raaghu-mfe/rds_pages/rds-page-edition/package.json
raaghu-mfe/rds_pages/rds-page-maintainance/package.json
raaghu-mfe/rds_pages/rds-page-settings/package.json
raaghu-mfe/rds_pages/rds-page-tenant/package.json
raaghu-mfe/rds_pages/rds-page-visualSetting/package.json
raaghu-mfe/rds_pages/rds-page-webhookSubscription/package.json

Added build script to the pages

---

raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.stories.tsx
raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx

Made some changes in visual setting component . 
Fixes #557 

Made some changes in visual setting component .

---

raaghu-elements/src/rds-offcanvas/rds-offcanvas.scss
raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx

Recreated Offcanvas Element.
Added button property.
Added option of canvas title. 
Changed all props. 
Deleted previous code.
Fixes #572 

Recreated Offcanvas Element

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.scss
raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx

Added offcanvas button toggle in action column of  data table Component
Fixes #574 

Added offcanvas button toggle in action column of  data table Component

---

raaghu-elements/src/rds-button/rds-button.scss
raaghu-elements/src/rds-button/rds-button.tsx

Added css in button element to resolve bug.
Fixes #579 

Added css in button element to resolve bug

---

raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
raaghu-elements/src/rds-progress-bar/rds-progress-bar.stories.tsx
raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
raaghu-elements/src/rds-table/rds-table.stories.tsx
raaghu-elements/src/rds-table/rds-table.tsx

create to do list table
Fixes #591 

create to do list table

---

raaghu-mfe/package.json
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/host/src/remote.d.ts
raaghu-mfe/rds_pages/host/webpack.config.js
raaghu-mfe/rds_pages/mfe-config.ts
raaghu-mfe/rds_pages/rds-page-auditLogs/package.json
raaghu-mfe/rds_pages/rds-page-auditLogs/public/index.html
raaghu-mfe/rds_pages/rds-page-auditLogs/src/App.tsx
raaghu-mfe/rds_pages/rds-page-auditLogs/webpack.config.js

> Added the dummy data in App.tsx file of audit-log page
> solved the bug for routing when the user is not logged in 
Fixes #608 #563 
- Test A
- Test B

Added the audit log page in anz site and solved the bug for routing when the user is not logged in

---

raaghu-components/src/index.ts
raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
raaghu-elements/src/rds-modal/rds-modal.stories.tsx

Solved the bug for Vertically centered modal

---

raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.scss
raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.stories.tsx
raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
raaghu-components/src/rds-comp-information/rds-comp-information.tsx
raaghu-elements/src/rds-badge/rds-badge.tsx
raaghu-elements/src/rds-chart-Pie/rds-chart-pie.stories.tsx
raaghu-elements/src/rds-chart-Pie/rds-chart-pie.tsx
raaghu-elements/src/rds-chart-area/rds-chart-area.stories.tsx
raaghu-elements/src/rds-chart-area/rds-chart-area.tsx

Added Dynamic entity property Component. 
Fixes #601 

 Added Dynamic entity property Component. 

---

raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
raaghu-elements/src/rds-table/rds-table.stories.tsx
raaghu-elements/src/rds-table/rds-table.tsx

Refactored Table element
Fixes #621 
Test B

Refactored Table element

---

raaghu-elements/src/rds-dropdown/rds-dropdown.stories.tsx
raaghu-elements/src/rds-dropdown/rds-dropdown.tsx

Refactored dropdown element
Fixes #614 

Refactored dropdown element

---

.storybook/main.js
.storybook/preview.js
package.json

Add Dark Light raaghu theme to storybook
Fixes #633

Add Dark Light raaghu theme to storybook

---

raaghu-components/src/index.ts
raaghu-elements/src/rds-offcanvas/rds-offcanvas.scss
raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx

Updated offcanvas Element.
Fixes #639 

Updated offcanvas Element.

---

raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-components/src/rds-comp-delivery-method/rds-comp-delivery-method.stories.tsx
raaghu-components/src/rds-comp-delivery-method/rds-comp-delivery-method.tsx
raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.scss
raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.stories.tsx
raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
raaghu-components/src/rds-comp-information/rds-comp-information.stories.tsx
raaghu-components/src/rds-comp-information/rds-comp-information.tsx
raaghu-components/src/rds-comp-integration/rds-comp-integration.tsx
raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.stories.tsx
raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
raaghu-elements/src/rds-icon/rds-icon.tsx
raaghu-elements/src/rds-modal/rds-modal.scss
raaghu-elements/src/rds-modal/rds-modal.stories.tsx
raaghu-elements/src/rds-modal/rds-modal.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.scss
raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx

Made some minor changes in components and elements.
Fixes #639 #640 #641 #642 #643 

 Made some minor changes in components and elements.

---

raaghu-elements/src/rds-badge/rds-badge.stories.tsx
raaghu-elements/src/rds-badge/rds-badge.tsx

Added Storybook elements in badge and fixed bug in Badge Element.
>
Fixes #616 #658 
- This change requires a documentation …

Added Storybook elements in badge and fixed bug in Badge Element.

---

package.json
raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
raaghu-components/src/rds-comp-role-list/rds-comp-role-list.stories.tsx
raaghu-components/src/rds-comp-role-list/rds-comp-role-list.tsx
raaghu-elements/src/rds-accordion/rds-accordion-item.tsx
raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
raaghu-elements/src/rds-accordion/rds-accordion.tsx
raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
raaghu-elements/src/rds-icon/rds-icon.tsx
raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
raaghu-elements/src/rds-side-nav/rds-side-nav-new.scss
raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
raaghu-elements/src/rds-toggle/rds-toggle.scss
raaghu-elements/src/rds-toggle/rds-toggle.stories.tsx
raaghu-elements/src/rds-toggle/rds-toggle.tsx
raaghu-mfe/rds_pages/rds-page-roles/src/App.tsx
raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.stories.tsx
raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx

updated accordion
Fixes #292 #663 #623 #656 #630 

updated accordion

---

raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
raaghu-elements/libs/types/colorvariant.ts
raaghu-elements/src/rds-big-number/rds-big-number.stories.tsx
raaghu-elements/src/rds-big-number/rds-big-number.tsx
raaghu-elements/src/rds-card/rds-card.scss
raaghu-elements/src/rds-widget/rds-widget.scss
raaghu-elements/src/rds-widget/rds-widget.tsx

Fixes #670 #671 
- Test A
- Test B

Enhancement in Big Number and Widget Element

---

raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.scss
raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx

Made changes in Dropdown list removed custom classes.
Fixes #664 

Made changes in Dropdown list removed custom classes.

---

raaghu-elements/src/rds-app-detail/rds-app-detail.scss
raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
raaghu-elements/src/rds-big-number/rds-big-number.tsx
raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx

Enhancement in app detail and solved the build error

---

raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
raaghu-elements/src/rds-dropdown/rds-dropdown.stories.tsx
raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
raaghu-elements/src/rds-side-nav/rds-side-nav-new.scss
raaghu-elements/src/rds-side-nav/rds-side-nav-new.stories.tsx

fixed side nav and added children button in dropdown

---

raaghu-elements/src/rds-carousel/rds-carousel.stories.tsx
raaghu-elements/src/rds-carousel/rds-carousel.tsx

Fixed some issues Carousel Element.
Fixes #686 

Fixed some issues Carousel Element.

---

raaghu-components/src/rds-comp-tenant-management/rds-comp-tenant-management.tsx
raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.stories.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx

Fixed error in  setting page , Tenant management component, top navigation component. 
Fixes #691 

Fixed error in  setting page , Tenant management component, top navigation component. 

---

raaghu-components/src/rds-comp-login/rds-comp-login.tsx
raaghu-elements/src/rds-modal/rds-modal.stories.tsx
raaghu-elements/src/rds-modal/rds-modal.tsx
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

Ui Enhancement of Login page and added modal in login page.
Fixes #721 

 Enhanced Ui of login page

---

raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx

Improved Edition Page.
Fixes #704 

Improved Edition page

---

raaghu-components/src/index.ts
raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.tsx
raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
raaghu-elements/src/rds-side-nav/rds-side-nav-new.scss
raaghu-mfe/rds_pages/host/src/bootstrap.tsx
raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
raaghu-mfe/rds_pages/rds-page-language/src/App.tsx

Added new features component to the raaghu react. and Improved edition page.
Fixes #766 #735

Added new features component to the raaghu react. and Improved edition page.

---

raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx

Added edition page and component.
Fixes #735 

Added edition page and component

---

raaghu-mfe/libs/shared/interceptor.ts
raaghu-mfe/libs/state-management/language/language-slice.ts
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-login/.env
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

added .env file and made changes in main.tsx of login

---

raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.scss
raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.tsx
raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx

>
> Enhancement in permission tree
- Test A
- Test B

committed-enhancement-in-permission-tree

---

raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
raaghu-elements/src/rds-select-list/rds-select-list.tsx
raaghu-mfe/libs/state-management/applications/applications-slice.ts
raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx

application page functionality modification

---

raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
raaghu-elements/src/rds-select-list/rds-select-list.tsx

Resolved build level issues.
#841: Resolved build level issues.

Resolved build level issues.

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
raaghu-elements/src/rds-icon/rds-icon.tsx
raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx

committed-text-template-UI-bug-fixed-for-functionality

---

raaghu-components/src/rds-comp-account/rds-comp-account.tsx
raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.tsx

>
solved build errors in settings page
> Please also list any …

settings page build errors solved

---

raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.stories.tsx
raaghu-mfe/libs/shared/interceptor.ts
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

URL changes from localhost to demoapi server

---

raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx

tenant page updated

---

raaghu-components/src/rds-comp-email/rds-comp-email.tsx
raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
raaghu-components/src/rds-comp-theme-new/rds-comp-theme-new.tsx
raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx

Development abp

---

raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
raaghu-components/src/rds-comp-login/rds-comp-login.tsx
raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
raaghu-elements/src/rds-input/rds-input.tsx
raaghu-elements/src/rds-select-list/rds-select-list.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

>
1) Completed UI for both language and text page 
2) Made necessary changes in RDSINPUT and RDSCHECKBOX which are now completed in term of functionality and will work in every scenario
3) Resolved the need to refresh in order to see dashboard after login  
4) Removed console error and warning which use to show on login screen 
Fixes #862 

UI of language and language text

---

raaghu-components/src/rds-comp-email/rds-comp-email.tsx
raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
raaghu-mfe/libs/state-management/settings/settings-slice.ts
raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx

settings page ui

---

raaghu-components/src/index.ts
raaghu-components/src/rds-comp-account/index.ts
raaghu-components/src/rds-comp-application-basic/index.ts
raaghu-components/src/rds-comp-claims/index.ts
raaghu-components/src/rds-comp-claims/rds-comp-claims.stories.tsx
raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
raaghu-components/src/rds-comp-feature-management/index.ts
raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
raaghu-components/src/rds-comp-security-logs/index.ts
raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-informations.tsx
raaghu-elements/src/rds-select-list/rds-select-list.tsx
raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx

> added a new component 
Fixes #879 
- Test A
- Test B

new claims component and code refactoring in Tenant Page

---

.github/workflows/development_storybookreact.yml

Storybook build issue

---

.github/workflows/development_storybookreact.yml

Ci-Cd pipeline storybook

---

raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx

Build issue storybook

---

raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
raaghu-mfe/rds_pages/rds-page-login/tsconfig.json

useLocation() issue is resolved

---

raaghu-components/src/rds-comp-account/rds-comp-account.tsx
raaghu-components/src/rds-comp-email/rds-comp-email.tsx
raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-informations.tsx
raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.tsx
raaghu-mfe/libs/state-management/claim-types/claim-types-slice.ts
raaghu-mfe/libs/state-management/user/user-slice.ts
raaghu-mfe/rds_pages/host/src/MyComponent.tsx
raaghu-mfe/rds_pages/host/tsconfig.json
raaghu-mfe/rds_pages/host/webpack.config.js
raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

Debugger removed.

---

raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx

> Created a directory list component and implemented it on File management page
Fixes #902 
- Test A
- Test B

created a directory list component

---

raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx

committed-permission-tree

---

raaghu-components/src/rds-comp-account/rds-comp-account.stories.tsx
raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.stories.tsx
raaghu-mfe/package.json

storybook build 

---

raaghu-components/src/rds-comp-directory-list/index.ts
raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx

> Added data table with it's different parent directory list folder data to the table and added search filter in it.
Fixes #925 
- Test A
- Test B

added data table and search filter in file management page

---

raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
raaghu-mfe/libs/state-management/user/user-slice.ts
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
user page organization unit functionality and UI
Fixes #892  and #893 
- Test A
- …

committed for user page organization unit functionality 

---

raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-informations.tsx
raaghu-components/src/rds-comp-tenant-management/rds-comp-tenant-management.tsx
raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
raaghu-mfe/rds_pages/rds-page-tenant/webpack.config.js

committed-feature-component

---

raaghu-components/src/index.ts
raaghu-components/src/rds-comp-identiy-resourcse-basic/index.ts
raaghu-components/src/rds-comp-identiy-resourcse-basic/rds-comp-identiy-resourcse-basic.stories.tsx
raaghu-components/src/rds-comp-identiy-resourcse-basic/rds-comp-identiy-resourcse-basic.test.tsx
raaghu-components/src/rds-comp-identiy-resourcse-basic/rds-comp-identiy-resourcse-basic.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/host/src/remote.d.ts
raaghu-mfe/rds_pages/host/webpack.config.js
raaghu-mfe/rds_pages/mfe-config.ts
raaghu-mfe/rds_pages/port-config.ts
raaghu-mfe/rds_pages/rds-page-identity-resources/package.json
raaghu-mfe/rds_pages/rds-page-identity-resources/public/index.html
raaghu-mfe/rds_pages/rds-page-identity-resources/src/App.tsx
raaghu-mfe/rds_pages/rds-page-identity-resources/src/IdentityResources/IdentityResources.tsx
raaghu-mfe/rds_pages/rds-page-identity-resources/src/index.ts
raaghu-mfe/rds_pages/rds-page-identity-resources/tsconfig.json
raaghu-mfe/rds_pages/rds-page-identity-resources/webpack.config.js

committed for identity resource page creation

---

raaghu-mfe/libs/state-management/index.ts
raaghu-mfe/libs/state-management/public.api.ts
raaghu-mfe/libs/state-management/scope/scope-slice.ts
raaghu-mfe/libs/state-management/scope/scope.models.ts
raaghu-mfe/rds_pages/rds-page-scope/src/Scope/Scope.tsx

databinding for api scopes page

---

raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx

>
> Added data table, search filter and breadcrumb in file management page.
Fixes #925  …

added data table, search filter and breadcrumb

---

raaghu-elements/src/rds-navtabs/rds-navtabs.scss
raaghu-mfe/rds_pages/mfe-config.ts
raaghu-mfe/rds_pages/port-config.ts
raaghu-mfe/rds_pages/rds-page-dynamicProperties/src/dynamicProperties/dynamicProperties.tsx

Build issue is resolved

---

raaghu-components/src/index.ts
raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
raaghu-components/src/rds-comp-properties-new/index.ts
raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.module.scss
raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.stories.tsx
raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.test.tsx
raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.tsx
raaghu-mfe/rds_pages/rds-page-identity-resources/src/IdentityResources/IdentityResources.tsx
raaghu-mfe/rds_pages/rds-page-identity-resources/src/bootstrap.tsx

>
Created properties component for identity resources page
Fixes #975 
- Test A
- Test …

committed for properties component 

---

raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx

created state management for file management module

---

raaghu-components/src/rds-comp-identiy-resourcse-basic/rds-comp-identiy-resourcse-basic.stories.tsx
raaghu-components/src/rds-comp-identiy-resourcse-basic/rds-comp-identiy-resourcse-basic.test.tsx
raaghu-mfe/libs/shared/UserAuth.ts
raaghu-mfe/libs/shared/interceptor.ts
raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

Date Range issue resolved.

---

raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
raaghu-mfe/libs/state-management/index.ts
raaghu-mfe/libs/state-management/public.api.ts
raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx

binded folder structure with apis in file management

---

.npmrc
package.json
raaghu-components/package.json
raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.stories.tsx
tsconfig.json

Storybook build issues are resolved

---

raaghu-mfe/rds_pages/host/public/index.html

>
##Solved Dropdown was not opening issue
Fixes #1009 
> Please describe the …

dropdown working on all pages

---

raaghu-components/src/rds-comp-login/rds-comp-login.tsx
raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-elements/src/rds-illustration/rds-illustration.tsx
raaghu-mfe/libs/state-management/identity-resources/identity-resources-slice.ts
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
resolved bugs #1002 #1004 #1006 #1023 #1024
Fixes #1002 #1004 #1006 #1023 #1024
- …

committed for bugs #1002 #1004 #1006 #1023 #1024

---

raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx

>
Fixes #1003 #1007 #1011 
> Please describe the tests that you ran to verify …

committed changes for tenant save button, security-log filter alignment

---

raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
raaghu-mfe/libs/state-management/roles/roles-slice.ts
raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx

roles page functionality completed

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-mfe/libs/state-management/user/user-slice.ts
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
resolved bugs  #1019  #1021 #1022 #1028 #1031 #1041
Fixes #1019  #1021 #1022 #1028 #1031 #1041 …

committed for  resolved bugs

---

raaghu-mfe/libs/main-menu/index.ts
raaghu-mfe/libs/main-menu/main-menu.ts
raaghu-mfe/libs/main-menu/url-forwarding.ts
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/host/src/remote.d.ts
raaghu-mfe/rds_pages/host/webpack.config.js
raaghu-mfe/rds_pages/mfe-config.ts
raaghu-mfe/rds_pages/port-config.ts
raaghu-mfe/rds_pages/rds-page-polls/package.json
raaghu-mfe/rds_pages/rds-page-polls/public/index.html
raaghu-mfe/rds_pages/rds-page-polls/src/App.tsx
raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.stories.tsx
raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
raaghu-mfe/rds_pages/rds-page-polls/src/bootstrap.tsx
raaghu-mfe/rds_pages/rds-page-polls/src/index.ts
raaghu-mfe/rds_pages/rds-page-polls/src/remote.d.ts
raaghu-mfe/rds_pages/rds-page-polls/tsconfig.json
raaghu-mfe/rds_pages/rds-page-polls/webpack.config.js
raaghu-mfe/rds_pages/rds-page-urlforwarding/.gitignore
raaghu-mfe/rds_pages/rds-page-urlforwarding/package.json
raaghu-mfe/rds_pages/rds-page-urlforwarding/public/index.html
raaghu-mfe/rds_pages/rds-page-urlforwarding/src/App.tsx
raaghu-mfe/rds_pages/rds-page-urlforwarding/src/bootstrap.tsx
raaghu-mfe/rds_pages/rds-page-urlforwarding/src/index.ts
raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
raaghu-mfe/rds_pages/rds-page-urlforwarding/tsconfig.json
raaghu-mfe/rds_pages/rds-page-urlforwarding/webpack.config.js

creation page Url forwarding

---

raaghu-components/src/index.ts
raaghu-components/src/rds-comp-polls-option/index.ts
raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.module.scss
raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.stories.tsx
raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.test.tsx
raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
raaghu-components/src/rds-comp-polls-question/index.ts
raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.module.scss
raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.stories.tsx
raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.test.tsx
raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
raaghu-mfe/libs/shared/UserAuth.ts
raaghu-mfe/libs/shared/interceptor.ts
raaghu-mfe/libs/state-management/identity-resources/identity-resources-slice.ts
raaghu-mfe/rds_pages/host/public/index.html
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx

>
created polls page question component 
Fixes #1061 
- Test A
- Test B

committed for polls page question component 

---

raaghu-mfe/rds_pages/host/webpack.config.js
raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx

Resolved build issues

---

package.json
raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.stories.tsx
raaghu-mfe/package.json

Version incremented for raaghu-themes

---

raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
raaghu-mfe/libs/state-management/apiScope/apiScope-slice.ts
raaghu-mfe/libs/state-management/applications/applications-slice.ts
raaghu-mfe/libs/state-management/claim-types/claim-types-slice.ts
raaghu-mfe/libs/state-management/edition/edition-slice.ts
raaghu-mfe/libs/state-management/forms/forms-slice.ts
raaghu-mfe/libs/state-management/language-text/language-text-slice.ts
raaghu-mfe/libs/state-management/language/language-slice.ts
raaghu-mfe/libs/state-management/roles/roles-slice.ts
raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
raaghu-mfe/libs/state-management/text-template/text-template-slice.ts
raaghu-mfe/libs/state-management/url-forwarding/url-forwarding-slice.ts
raaghu-mfe/libs/state-management/user/user-slice.ts
raaghu-mfe/rds_pages/host/public/index.html

dropdown issue and datatable entry last value first

---

raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx

committed changes for admin offcanvas UI

---

raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx

>
>Adding data binding of directory list component in file management page
Fixes #915  …

adding functionality in directory list component

---

raaghu-components/package.json
raaghu-elements/package.json
raaghu-mfe/package.json

raaghu-react-elments version is change

---

raaghu-components/src/index.ts
raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
raaghu-mfe/libs/state-management/polls/polls-slice.ts
raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx

>
completed  state management of polls page
Fixes #1086 
- Test A
- Test B

committed for state management of polls page

---

raaghu-mfe/libs/state-management/user/user-slice.ts
raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
Fixes #1018 #1009 #1017 #1016 #1084 
> Please describe the tests that you …

solved roles users edition page bugs

---

raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx

>
> Added data binding for the delete and Rename Functionality
Fixes #1126 #1127 
- …

data binding for Rename and Delete funstionality

---

raaghu-mfe/libs/state-management/host/host-slice.ts
raaghu-mfe/libs/state-management/index.ts
raaghu-mfe/libs/state-management/public.api.ts
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

Fixes #1106 #1129 
- Test A
- Test B

bugs in user and login navigation issue solved

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

action in the data table issue solved

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
raaghu-mfe/libs/state-management/index.ts
raaghu-mfe/libs/state-management/polls/polls-slice.ts
raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx

>
committed for data-table changes and polls option component
Fixes #1062  #1119 
- …

committed for data-table changes and polls option component

---

raaghu-elements/generate-react-cli.json
raaghu-mfe/package.json
utils/create.js

Change import statement with export statement

---

raaghu-components/src/rds-comp-change-password/rds-comp-change-password.stories.tsx
raaghu-components/src/rds-comp-change-password/rds-comp-change-password.test.tsx

Storybook build issues

---

raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.scss
raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.scss
raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx

>
> added functionality for search filter
Fixes #1142 
- Test A
- Test B

changes in search filter functionality

---

raaghu-mfe/libs/state-management/chats/chats-slice.ts

>
state management for chat module
Fixes #1165 
> Please describe the tests …

state management for chat module

---

raaghu-core/.npmrc
raaghu-core/src/services/permission-service.tsx

Build issues resolved

---

raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
raaghu-mfe/libs/main-menu/main-menu.ts
raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
raaghu-mfe/rds_pages/rds-page-paymentRequests/src/paymentRequests/paymentRequests.tsx

committed-blogger-bug

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
raaghu-components/src/rds-comp-login/rds-comp-login.tsx
raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-elements/src/rds-button/rds-button.tsx
raaghu-elements/src/rds-button/rds-button.types.ts
raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
raaghu-mfe/libs/state-management/settings/settings-slice.ts
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx

Fixes #1005 , #1197 #1191 
- Test A
- Test B

offcanvas blacking out, top-nav in login, datatable action box size

---

raaghu-mfe/libs/shared/interceptor.ts

interceptor added into lib/service

---

raaghu-components/src/index.ts
raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
raaghu-components/src/rds-comp-file-mover/index.ts
raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.tsx
raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
raaghu-elements/src/rds-icon-label/rds-icon-label.tsx
raaghu-mfe/libs/shared/service-proxy.ts
raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx

>
> Create a component and worked on data binding
Fixes #1214 
- Test A
- Test B

create a file mover component

---

raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.scss
raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
raaghu-mfe/libs/state-management/settings/settings-slice.ts
raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
raaghu-mfe/rds_pages/rds-page-blogs/webpack.config.js
raaghu-mfe/rds_pages/rds-page-elements/src/elements/elements.tsx
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx

solved bugs in pages

---

raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

breadcrum applied for all pages

---

raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
raaghu-mfe/libs/state-management/apiScope/apiScope-slice.ts
raaghu-mfe/libs/state-management/blogger/blogger-slice.ts
raaghu-mfe/libs/state-management/language/language-slice.ts
raaghu-mfe/libs/state-management/menus/menus-slice.ts
raaghu-mfe/libs/state-management/payment-plans/paymentPlans-slice.ts
raaghu-mfe/libs/state-management/personal-data/personal-data-slice.ts
raaghu-mfe/libs/state-management/polls/polls-slice.ts
raaghu-mfe/libs/state-management/roles/roles-slice.ts
raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
raaghu-mfe/libs/state-management/user/user-slice.ts
raaghu-mfe/rds_pages/rds-page-forms-view/src/FormsView/FormsView.tsx
raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx

>
> Changes in the slice files of different pages
Fixes #1249 
- Test A
- Test B

changes in service proxy files of different pages

---

raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.tsx
raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
raaghu-components/src/rds-comp-menus-directories/rds-comp-menus-directories.tsx
raaghu-mfe/libs/state-management/index.ts
raaghu-mfe/libs/state-management/menus/menus-slice.ts
raaghu-mfe/libs/state-management/public.api.ts
raaghu-mfe/rds_pages/rds-page-menus/src/menus/menus.tsx

Fixes #1248 #1257 #1240 #1281 
- Test A
- Test B

Added menus directory component and added menus page

---

raaghu-elements/src/rds-select-list/rds-select-list.tsx
raaghu-mfe/rds_pages/host/src/PageComponent.ts
utils/create.js

Added parent items to the list items while running the create module command. and added select list.
Fixes #1306 

Added parent items to the list items while running the create module command. and added select list.

---

raaghu-mfe/rds_pages/rds-page-menus/src/menus/menus.tsx

Removed menu item heading from menus page.
Fixes #1240 
- Test A
- Test B

removed menu item heading from menus page

---

raaghu-mfe/rds_pages/host/src/Main.tsx

main.tsx error removed

---

raaghu-mfe/rds_pages/mfe-config.ts
raaghu-mfe/rds_pages/port-config.ts

committed changes for removing rdscomponents page

---

package.json
raaghu-mfe/package.json
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

Version changed for raaghu-react-core

---

package.json
raaghu-mfe/package.json

raaghu-themes version is incremented.

---

raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

Build issues are resolved.

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
raaghu-elements/src/rds-datepicker/rds-datepicker.scss
raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
raaghu-elements/src/rds-input-group/rds-input-group.tsx
raaghu-mfe/libs/state-management/text-template/text-template-slice.ts
raaghu-mfe/libs/state-management/user/user-slice.ts
raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
resolved issues #1207 #1229 #1300 #1330.
Fixes #1207 #1229 #1300 #1330
- Test A
- …

committed for issues #1207 #1229 #1300 #1330

---

raaghu-mfe/rds_pages/rds-page-menus/webpack.config.js
raaghu-mfe/rds_pages/rds-page-myaccount/webpack.config.js
raaghu-mfe/rds_pages/rds-page-pages/webpack.config.js
raaghu-mfe/rds_pages/rds-page-personaldata/webpack.config.js
raaghu-mfe/rds_pages/rds-page-scope/webpack.config.js
raaghu-mfe/rds_pages/rds-page-settings/webpack.config.js
raaghu-mfe/rds_pages/rds-page-undermaintainance/webpack.config.js
raaghu-mfe/rds_pages/rds-page-urlforwarding/webpack.config.js
raaghu-mfe/rds_pages/rds-page-visualSetting/webpack.config.js
raaghu-mfe/rds_pages/rds-page-webhookSubscription/webpack.config.js

committed  for build time optimize

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
raaghu-mfe/package.json
raaghu-mfe/rds_pages/host/public/index.html
raaghu-mfe/rds_pages/host/src/App.tsx
raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
> Check UI and Functionality for Users and Claim types page
>Check UI and Functionality for Users and Claim types page
Fixes #1286 
- Test A
- Test B

Changes are commited for users

---

raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.tsx
raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
raaghu-elements/src/rds-input-group/rds-input-group.tsx
raaghu-mfe/libs/proxy/core/OpenAPI.ts
raaghu-mfe/libs/shared/interceptor.ts
raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
raaghu-mfe/libs/state-management/personal-data/personal-data-slice.ts
raaghu-mfe/libs/state-management/polls/polls-slice.ts
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
raaghu-mfe/rds_pages/rds-page-newsletters/src/newsletters/Newsletters.tsx

>
> Changes in slice files and file management data binding
Fixes #1196 #1328 #1105 #1221  …

changes in file management page

---

raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

Resolved the build error in Tenant page , language, and language text page.
Fixes #1372

Resolved the build error in Tenant page , language, and language text page

---

raaghu-mfe/rds_pages/rds-page-dynamicProperties/src/dynamicProperties/dynamicProperties.tsx
raaghu-mfe/rds_pages/rds-page-webhookSubscription/webpack.config.js

Build issues are resolved

---

.storybook/preview.js
raaghu-elements/src/rds-toast/rds-toast.stories.tsx
raaghu-elements/src/rds-toast/rds-toast.tsx

Created toast element and it types
Fixes #1355 

Created toast element and it types

---

raaghu-elements/src/rds-toast/rds-toast.stories.tsx
raaghu-elements/src/rds-toast/rds-toast.tsx
raaghu-mfe/rds_pages/host/src/PageComponent.ts

Resolved 1361 and added icon width, height, and fill in element
Fixes #1361 #1355 

Resolved 1361 and added icon width, height, and fill in element

---

raaghu-mfe/libs/state-management/tags/tags-slice.ts

Fixes 
#1352 
> Admin>>CMS>>Tags>>Unable to add new tag
- Test A
- Test B

Resolve Add, Edit & Delete tag functionality

---

raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
raaghu-mfe/libs/state-management/security-logs/security-logs-slice.ts
raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
raaghu-mfe/rds_pages/rds-page-paymentRequests/src/paymentRequests/paymentRequests.tsx
raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx

>
committed for issue #1340 and  #1363
Fixes #1340   #1363
- Test A
- Test B

committed for issue #1340 and  #1363

---

package.json
raaghu-mfe/package.json

raaghu-themes version incremented

---

raaghu-mfe/libs/proxy/core/OpenAPI.ts
raaghu-mfe/libs/shared/interceptor.ts
raaghu-mfe/rds_pages/host/src/Main.tsx

API_URL is stored into a sessionStorage variable

---

raaghu-mfe/libs/state-management/roles/roles-slice.ts

updated roles-slice file
>
> Please describe the tests that …

updated roles-slice file

---

raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx

Resolved the issue in profile of top navigation.
Fixes #1437 

Resolved the issue in profile of top navigation.

---

raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
raaghu-elements/src/rds-input/rds-input.tsx
raaghu-elements/src/rds-select-list/rds-select-list.tsx

Fixes 
#1422 
#1423 
> DROPDOWN: Mouse cursor: pointer should be on over on dropdown element.
> NAVTAB: Mouse cursor: pointer should be on over on navtab element.
- Test A
- Test B

Add class to navtab and dropdown for handcursor

---

raaghu-components/src/rds-comp-elements/code_snippet.ts
raaghu-components/src/rds-comp-elements/elements/accordion.tsx
raaghu-components/src/rds-comp-elements/elements/addressDetail.tsx
raaghu-components/src/rds-comp-elements/elements/alert.tsx
raaghu-components/src/rds-comp-elements/elements/appDetail.tsx
raaghu-components/src/rds-comp-elements/elements/avatar.tsx
raaghu-components/src/rds-comp-elements/elements/badge.tsx
raaghu-components/src/rds-comp-elements/rds-comp-elements.tsx
raaghu-components/src/rds-comp-top-navigation/element-list.ts
raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-elements/src/rds-badge/rds-badge.stories.tsx
raaghu-mfe/rds_pages/rds-page-elements/src/elements/elements.tsx

Add element Dropdown in top navigation
Add dynamic routing for elements
Add Alert, Accordion, Address Detail,Alert, App detail, badge element in Element Page.
Fixes #1063 

Implemented Element Page functionality.

---

raaghu-components/src/rds-comp-login/rds-comp-login.tsx
raaghu-mfe/libs/proxy/core/OpenAPI.ts
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/host/src/openid.config.ts
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

>Login page > Remember me functionality 
> Login page > Remember me functionality 
Fixes #1239
- Test A
- Test B

Remember me login Page

---

raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
raaghu-elements/src/rds-button/rds-button.tsx
raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx

>
>issues on audit logs, Tenant and personal data page
Fixes #1451 #1455 #1457 #1465
- …

Application issue, canvas title issue, audit log spacing issue

---

raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx
raaghu-components/src/rds-comp-components/code_snippet.ts
raaghu-components/src/rds-comp-components/components/cache.tsx
raaghu-components/src/rds-comp-components/components/cardDetailList.tsx
raaghu-components/src/rds-comp-components/rds-comp-components.tsx
raaghu-components/src/rds-comp-elements/rds-comp-elements.tsx
raaghu-components/src/rds-comp-top-navigation/components-list.ts
raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
raaghu-mfe/libs/main-menu/elements.ts
raaghu-mfe/rds_pages/host/.env
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-components/src/App.tsx
raaghu-mfe/rds_pages/rds-page-components/src/components/components.tsx
raaghu-mfe/rds_pages/rds-page-elements/src/App.tsx

Implemented component page and resolve all the issues related to it.
Fixes #1491 #1490 #1475 #1153 #1489

Implemented component page and resolve all the issues related to it.

---

raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
Admin>>Dashboard>>Tenant breadcrumb is showing for dashboard 
Fixes #1443
- Test A
- …

committed for tenant breadcrumb issue

---

raaghu-mfe/rds_pages/host/.env

URL is corrected

---

raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx

active class

---

package.json
raaghu-mfe/package.json

raaghu-themes version is incremented

---

package.json
raaghu-mfe/package.json

raaghu-react-core version is incremented

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-elements/src/rds-avatar/rds-avatar.tsx
raaghu-elements/src/rds-illustration/rds-illustration.tsx
raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
raaghu-mfe/libs/proxy/core/OpenAPI.ts

Fixes #1507 
>[Data table component>>Remove inline styling](https://github.com/Wai-Technologies/raaghu-react/issues/1507)
- Test A …

Removed inline CSS form Datatable comp, avatar and illustration elements.

---

raaghu-components/src/rds-comp-new-menu/rds-comp-new-menu.tsx
raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
raaghu-components/src/rds-comp-url-forwardings/rds-comp-url-forwardings.tsx
raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx
raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx

>
Admin>>Off canvas>>Save button should disabled until all mandatory fields are filled 
Fixes #1448 …

committed for  issue #1448

---

raaghu-mfe/rds_pages/host/src/Main.tsx

Inner page top is set

---

raaghu-components/src/rds-comp-charts/charts/boolean.tsx
raaghu-components/src/rds-comp-charts/code_snippet.ts
raaghu-components/src/rds-comp-top-navigation/charts-list.ts
raaghu-components/src/rds-comp-top-navigation/multi-level-dropdown.tsx
raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
raaghu-mfe/libs/main-menu/main-menu.ts

Added multi-level dropdown in top navigation
Fixes #1546  #1536 #1538 #1550 #1553 #1555 

Added multi-level dropdown in top navigation

---

raaghu-components/src/rds-comp-email/rds-comp-email.tsx
raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx
raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx

>
>Fixes in UI
Fixes #1551 #1457 #1450 #1554 #1518 #1465 #1430 
- Test A
- Test B

Bugs Fixes in UI

---

raaghu-mfe/rds_pages/port-config.ts

polls page

---

raaghu-components/src/rds-comp-account/rds-comp-account.tsx
raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.stories.tsx
raaghu-components/src/rds-comp-api-scope-basic-resource/rds-comp-api-scope-basic-resource.tsx
raaghu-components/src/rds-comp-background-image/rds-comp-background-image.tsx
raaghu-components/src/rds-comp-claim/rds-comp-claim.tsx

Resolved bugs in Components
>
Resolved bugs in Components.
Fixes #1153 

Resolved bugs in Components

---

raaghu-components/src/rds-comp-elements/elements/teamMember.tsx
raaghu-components/src/rds-comp-elements/elements/testimonial.tsx
raaghu-components/src/rds-comp-elements/elements/textArea.tsx
raaghu-components/src/rds-comp-elements/elements/textEditor.tsx
raaghu-components/src/rds-comp-elements/elements/toast.tsx
raaghu-components/src/rds-comp-elements/elements/toggle.tsx
raaghu-components/src/rds-comp-elements/elements/tooltip.tsx
raaghu-components/src/rds-comp-elements/elements/videoPlayer.tsx
raaghu-components/src/rds-comp-elements/elements/websiteMatrix.tsx
raaghu-components/src/rds-comp-elements/elements/widget.tsx

Added  Elements in element page.
Fixes #1063 

Added  Elements in element page.

---

raaghu-elements/__tests__/rds-banner.test.tsx

Created test file for rds-banner
Fixes #1580 

Created test file for rds-banner

---

raaghu-components/src/rds-comp-elements/code_snippet.ts
raaghu-components/src/rds-comp-elements/elements/rating.tsx
raaghu-components/src/rds-comp-elements/elements/reviewCategory.tsx
raaghu-components/src/rds-comp-elements/elements/scrollspy.tsx
raaghu-components/src/rds-comp-elements/elements/search.tsx
raaghu-components/src/rds-comp-elements/elements/selectList.tsx

Added code_snippet and  elements in Element Page. 
Fixes #1063 

Added code_snippet and  elements in Element Page.

---

raaghu-elements/__tests__/rds-benefit.test.tsx

Created test file for rds-benefit element.
Fixes #1580 

Created test file for rds-benefit element.

---

raaghu-components/src/rds-comp-elements/elements/sideNav.tsx
raaghu-components/src/rds-comp-elements/elements/size.tsx
raaghu-components/src/rds-comp-elements/elements/spinner.tsx
raaghu-components/src/rds-comp-elements/elements/stat.tsx
raaghu-components/src/rds-comp-elements/elements/stepper.tsx

Added more elements.
Fixes #1063 

Added more elements

---

raaghu-components/src/rds-comp-elements/elements/table.tsx
raaghu-components/src/rds-comp-elements/elements/tag.tsx
raaghu-components/src/rds-comp-top-navigation/element-list.ts

Added all element in element page.
Fixes #1063 #1574 

Added all element in element page.

---

raaghu-elements/__tests__/rds-big-number.test.tsx

Created test file for rds-bignumber element.
Fixes #1580

Created test file for rds-bignumber element.

---

raaghu-components/src/rds-comp-components/components/account.tsx
raaghu-components/src/rds-comp-components/components/addressInput.tsx
raaghu-components/src/rds-comp-components/components/adminDashboard.tsx
raaghu-components/src/rds-comp-components/components/apiResourceBasic.tsx
raaghu-components/src/rds-comp-components/components/apiScopeResource.tsx

Added component in component page. 
Fixes #1153 

Added component in component page. 

---

raaghu-elements/__tests__/rds-button-group.test.tsx

created test file for rds-button-group element.
Fixes #1580 

created test file for rds-button-group element.

---

raaghu-components/src/rds-comp-components/components/calender.tsx
raaghu-components/src/rds-comp-components/components/claim.tsx
raaghu-components/src/rds-comp-components/components/clientResource.tsx
raaghu-components/src/rds-comp-components/components/contactInformation.tsx
raaghu-components/src/rds-comp-components/components/contactUs.tsx

Added few more components.
Fixes #1153 

Added few more components

---

raaghu-components/src/rds-comp-components/components/cookiesSection.tsx
raaghu-components/src/rds-comp-components/components/customerReview.tsx
raaghu-components/src/rds-comp-components/components/dataTable.tsx
raaghu-components/src/rds-comp-components/components/deliveryMethod.tsx
raaghu-components/src/rds-comp-components/components/edition.tsx

Added few more components till edition
Fixes #1153 

Added few more components till edition

---

raaghu-elements/__tests__/rds-carousel.test.tsx

created test file for rds-carousel element.
Fixes #1580

created test file for rds-carousel element.

---

raaghu-components/src/rds-comp-components/components/editLanguageText.tsx
raaghu-components/src/rds-comp-components/components/editionList.tsx
raaghu-components/src/rds-comp-components/components/editionNewBasic.tsx
raaghu-components/src/rds-comp-components/components/email.tsx
raaghu-components/src/rds-comp-components/components/emailSetting.tsx

Added few more components till Email setting
Fixes #1153 

Added few more components till Email setting

---

raaghu-components/src/rds-comp-components/code_snippet.ts
raaghu-components/src/rds-comp-components/components/emailSettingNew.tsx
raaghu-components/src/rds-comp-components/components/faq.tsx
raaghu-components/src/rds-comp-components/components/feeds.tsx
raaghu-components/src/rds-comp-top-navigation/components-list.ts

Added few more components till Feeds.
Fixes #1153 

Added few more components till Feeds.

---

raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.stories.tsx
raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx

Fixed the bug in Email setting component.
Fixes #1153 

Fixed the bug in Email setting component.

---

raaghu-components/src/rds-comp-components/code_snippet.ts
raaghu-components/src/rds-comp-components/components/forgotPassword.tsx
raaghu-components/src/rds-comp-components/components/identityMangement.tsx
raaghu-components/src/rds-comp-components/components/identityResourcesBasic.tsx
raaghu-components/src/rds-comp-top-navigation/components-list.ts

Added more component in component  Page.
Fixes #1153 

added more component in component  Page

---

raaghu-components/src/rds-comp-components/components/information.tsx
raaghu-components/src/rds-comp-components/components/integration.tsx
raaghu-components/src/rds-comp-components/components/invoice.tsx

Added component till Invoice component.
Fixes #1153 

Added component till Invoice component

---

raaghu-components/src/rds-comp-components/components/linkedAccount.tsx
raaghu-components/src/rds-comp-components/components/login.tsx
raaghu-components/src/rds-comp-components/components/loginAttempt.tsx

Added component till Invoice component.
Fixes #1153 

Added component till Login Attempt component

---

raaghu-components/src/rds-comp-components/code_snippet.ts
raaghu-components/src/rds-comp-components/components/editProfile.tsx
raaghu-components/src/rds-comp-components/components/mySetting.tsx
raaghu-components/src/rds-comp-components/components/newClaimType.tsx
raaghu-components/src/rds-comp-components/components/newLanguage.tsx
raaghu-components/src/rds-comp-components/components/newProperties.tsx
raaghu-components/src/rds-comp-components/components/newRole.tsx

Added code snippet and components till New language.
Fixes #1153 

Added code snippet and components till New language.

---

raaghu-components/src/rds-comp-components/code_snippet.ts

Updated code_snippet of components.
Fixes #1153 

Updated code_snippet of components

---

raaghu-elements/__tests__/rds-color-switcher.test.tsx
raaghu-elements/src/rds-color-switcher/rds-color-switcher.tsx

Created test file for color-picker and color-switcher
Fixes #1580 

Created test file for color-picker and color-switcher

---

raaghu-elements/__tests__/rds-counter.test.tsx
raaghu-elements/src/rds-button/rds-button.tsx
raaghu-elements/src/rds-button/rds-button.types.ts
raaghu-elements/src/rds-counter/rds-counter.tsx

Written test file for counter. and updated necessary files used in testing this component.
Fixes #1580

Written test file for counter.

---

raaghu-components/src/rds-comp-components/components/review.tsx
raaghu-components/src/rds-comp-components/components/securiety.tsx
raaghu-components/src/rds-comp-components/components/securietyLogs.tsx
raaghu-components/src/rds-comp-components/components/shippingAddress.tsx
raaghu-components/src/rds-comp-components/components/sideNavigation.tsx

Added component till side navigation.
Fixes #1153 

Added component till side navigation.

---

raaghu-components/src/rds-comp-components/components/subscription.tsx
raaghu-components/src/rds-comp-components/components/teams.tsx
raaghu-components/src/rds-comp-components/components/tenantDashboard.tsx
raaghu-components/src/rds-comp-components/components/tenantList.tsx

Added component till Tenant List.
Fixes #1153 

Added component till Tenant List.

---

raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx

Resolved bug in edit profile component.
Fixes #1643 

Resolved bug in edit profile component.

---

raaghu-components/src/rds-comp-notification-settings/rds-comp-notification-settings.tsx
raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.stories.tsx
raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.tsx

Resolved bugs in components. 
Fixes #1635 

Resolved bugs in components.

---

raaghu-components/src/rds-comp-components/code_snippet.ts
raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.stories.tsx
raaghu-components/src/rds-comp-integration/rds-comp-integration.stories.tsx
raaghu-components/src/rds-comp-integration/rds-comp-integration.tsx

Resolved bugs in components. 
Fixes #1153 

Added code_snippet till tenant List.

---

raaghu-elements/__tests__/rds-dropdown.test.tsx
raaghu-elements/__tests__/rds-fab-menu.test.tsx
raaghu-elements/__tests__/rds-feature-list.test.tsx
raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
raaghu-elements/src/rds-fab-menu/rds-fab-menu.tsx
raaghu-elements/src/rds-feature-list/rds-feature-list.tsx

Created test for dropdown, fab Menu, feature list.
Fixes #1580 

Created test for dropdown, fab Menu, feature list.

---

raaghu-elements/src/rds-input/rds-input.tsx

Add Validation and resolve bug in Input Element.
Fixes #1661 

Resolve bug in Input element

---

raaghu-elements/__tests__/rds-popular-page.test.tsx
raaghu-elements/__tests__/rds-price.test.tsx
raaghu-elements/__tests__/rds-product-image.test.tsx
raaghu-elements/src/rds-popular-page/rds-popular-page.tsx
raaghu-elements/src/rds-price/rds-price.tsx
raaghu-elements/src/rds-product-image/rds-product-image.tsx

Added test file for popular page.
Fixes #1580 

Added test file for popular page.

---

raaghu-components/src/rds-comp-components/components/tenantManagement.tsx
raaghu-components/src/rds-comp-components/components/tenantSetting.tsx
raaghu-components/src/rds-comp-components/components/testimonials.tsx
raaghu-components/src/rds-comp-components/components/themeNew.tsx
raaghu-components/src/rds-comp-components/components/urlForwarding.tsx

Added components  till Url Forwarding.
Fixes #1153 

Added components  till Url Forwarding .

---

raaghu-elements/__tests__/rds-navtabs.test.tsx
raaghu-elements/__tests__/rds-notification.test.tsx

Added  test script for navtabs elements
Fixes #1581 

Created test script for navtabs elements

---

raaghu-elements/src/rds-alert/rds-alert.tsx

Enhanced Alert element
Fixes #1671 

Enhanced Alert element

---

raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
raaghu-mfe/rds_pages/rds-page-myaccount/src/my-account/my-account.tsx

>
Fixes #1457 #1594 #1677 
> Please describe the tests that you ran to verify …

committed  for offcanvas title canvas issue and change password input

---

raaghu-components/src/rds-comp-email/rds-comp-email.tsx
raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx

Fixes #1631 #1551 
- Test A
- Test B

settings page offcanvas issue fixed

---

raaghu-elements/__tests__/rds-range.test.tsx

Created test script for rds-range
Fixes #1581 

Created test script for rds-range

---

raaghu-elements/__tests__/rds-size.test.tsx
raaghu-elements/__tests__/rds-spinner.test.tsx
raaghu-elements/__tests__/rds-stat.test.tsx
raaghu-elements/__tests__/rds-tooltip.test.tsx
raaghu-elements/src/rds-size/rds-size.tsx
raaghu-elements/src/rds-stat/rds-stat.tsx

Added test files for select-list, size, spinner and tooltip
Fixes #1580
- [] I have made corresponding changes to the documentation

Added test files for spinner and tooltip

---

raaghu-elements/__tests__/rds-rating.test.tsx

Created test script for rds-rating 
Fixes #1581 

Created test script for rds-rating 

---

raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx

Fixes 
#1655 
#1628 
> Admin>>Application>>Save and cancel button should left aligned
> Admin>>Administration>>Blogs>>Screen should get fade after opening off canvas
- Test A
- Test B

PR for bug #1655, #1628

---

raaghu-components/src/rds-comp-components/components/userBasic.tsx
raaghu-components/src/rds-comp-components/components/userClaim.tsx
raaghu-components/src/rds-comp-components/components/userManagement.tsx
raaghu-components/src/rds-comp-components/components/userPermission.tsx
raaghu-components/src/rds-comp-components/components/userPermissionNew.tsx

Added more components in component.
Fixes #1153 

Added more components in component.

---

raaghu-elements/__tests__/rds-stepper.test.tsx
raaghu-elements/__tests__/rds-text-area.test.tsx
raaghu-elements/__tests__/rds-text-editor.test.tsx
raaghu-elements/__tests__/rds-toast.test.tsx

Created test script for rds-stepper element
Fixes #1581 

Created test script for rds-stepper element

---

raaghu-elements/__tests__/rds-chart-area.test.tsx
raaghu-elements/__tests__/rds-dropdown-list.test.tsx

Created test script of rds-chart-area element
Fixes #1581 

Created test script of rds-chart-area element

---

raaghu-components/src/rds-comp-login/rds-comp-login.tsx
raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
raaghu-mfe/rds_pages/rds-page-blogpost/src/blog-post/blog-post.tsx
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
raaghu-mfe/rds_pages/rds-page-tags/src/tags/tags.tsx
raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx

>
> Login with tenant functionality and screen fade issues
Fixes #1698 #1520 
- Test A …

switch tenant functionality and offcanvas backdrop issue

---

raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
raaghu-elements/src/rds-button-group/rds-button-group.tsx

Monthly option is set as default

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx

updated data table component.
Fixes #1613 

updated data table component.

---

raaghu-components/src/rds-comp-components/code_snippet.ts
raaghu-components/src/rds-comp-components/components/userTable.tsx
raaghu-components/src/rds-comp-top-navigation/components-list.ts
raaghu-components/src/rds-comp-user-permission-new/rds-comp-user-permission-new.tsx
raaghu-components/src/rds-comp-user-permission/rds-comp-user-permission.tsx

Added remaining components in component Page.
Fixes #1153  

Added remaining components in component Page.

---

raaghu-elements/src/rds-alert/rds-alert.tsx
raaghu-mfe/libs/state-management/host/host-slice.ts
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

Handling Error for login error.
Fixes #1599 

Handling Error for login error

---

raaghu-elements/__tests__/rds-double-range.test.tsx
raaghu-elements/__tests__/rds-side-nav.test.tsx

Created Test script for rds-double-range and side-nave element
Fixes #1581 

Created Test script for rds-double-range and side-nave element

---

raaghu-components/src/rds-comp-login/rds-comp-login.tsx
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

Added alert message in login component instead of login page.
Fixes #1722 

Added alert message in login component instead of login page.

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-components/src/rds-comp-email/rds-comp-email.tsx
raaghu-components/src/rds-comp-login/rds-comp-login.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
> changes made in breadcrum, settings page and date-time format
Fixes #1633 #1450 #1692 …

Breadcrum issues, date and time format

---

raaghu-elements/src/rds-toast/rds-toast.tsx
raaghu-mfe/package.json
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx

Updated raaghu-react-core and main.tsx
Fixes #1708 #1722  

Updated raaghu-react-core and main.tsx

---

raaghu-components/src/rds-comp-syntax-highlighter/rds-comp-syntax-highlighter.tsx

fixed issue 1697

---

raaghu-components/src/rds-comp-login/rds-comp-login.tsx
raaghu-mfe/libs/state-management/host/host-slice.ts
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

added dynamic message for alert.
Fixes #1737 

added dynamic message for alert.

---

raaghu-elements/__tests__/__snapshots__/rds-chart-area.test.tsx.snap
raaghu-elements/__tests__/__snapshots__/rds-toggle.test.tsx.snap
raaghu-elements/__tests__/rds-listgroup.test.tsx
raaghu-elements/__tests__/rds-scrollspy.test.tsx
raaghu-elements/__tests__/rds-side-nav.test.tsx
raaghu-elements/__tests__/rds-websitematrix.test.tsx
raaghu-elements/src/rds-list-group/rds-list-group.tsx
raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
raaghu-elements/src/rds-website-matrix/rds-website-matrix.tsx

committed test cases scrollspy ,sidenav

---

raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
raaghu-elements/src/rds-select-list/rds-select-list.tsx
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx

>
> Added Tenant activation state in New Tenant 
Fixes #1702 
- Test A
- Test B

added tenant activation state in Tenant page

---

raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx

Added alert functionality in blogger.
Fixes #1694 

Added alert functionality in blogger.

---

raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx

added error alert too in blogger
Fixes #1694 

added error alert too in blogger

---

raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx

updated language.tsx
Fixes #1694 

updated language.tsx

---

package.json
raaghu-mfe/package.json

raaghu-themes version incremented to 0.0.30

---

raaghu-mfe/libs/state-management/organization-tree/organization-tree-slice.ts
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx

>
Fixes #1373  #1736  #1730  #1733  #1731 
> Please describe the tests that …

fixed bugs #1373 #1736 #1730 #1733 #1731

---

raaghu-mfe/libs/state-management/personal-data/personal-data-slice.ts
raaghu-mfe/rds_pages/rds-page-personaldata/src/personal-data/personal-data.tsx

>
> Request Personal Data Issue
Fixes #1451 
- Test A
- Test B

request personal data issue

---

package.json
raaghu-mfe/package.json

raaghu-themes version is decremented

---

raaghu-mfe/libs/state-management/comments/comments-slice.ts

Did state management for Comment Page. 
Fixes #1081 

Did state management for Comment Page.

---

raaghu-mfe/rds_pages/rds-page-comments/src/comments/comments.tsx

data binding for comment page.
Fixes #1080 

data binding for comment page.

---

raaghu-components/src/rds-comp-elements/elements/accordion.tsx

Updated Accordion.tsx

---

raaghu-components/__tests__/rds-comp-feeds.test.tsx
raaghu-components/src/rds-comp-feeds/rds-comp-feeds.tsx
raaghu-elements/src/rds-rating/rds-rating.tsx

Added test file for feeds component.
Fixes #1595 

Added test file for feeds component.

---

raaghu-mfe/rds_pages/host/src/Main.tsx

Resolved routing issue while opening CMS>>pages
Fixes #1766

Resolved routing issue while opening CMS>>pages

---

raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx

Edited Off canvas heading instead.
Fixes #1756 

Edited Off canvas heading instead.

---

raaghu-elements/__tests__/rds-teammember.test.tsx

Jest changes for unwanted imports

---

raaghu-mfe/rds_pages/rds-page-blogpost/package.json
raaghu-mfe/rds_pages/rds-page-chart/package.json
raaghu-mfe/rds_pages/rds-page-chart/webpack.config.js
raaghu-mfe/rds_pages/rds-page-components/package.json
raaghu-mfe/rds_pages/rds-page-components/webpack.config.js
raaghu-mfe/rds_pages/rds-page-newsletters/package.json
raaghu-mfe/rds_pages/rds-page-newsletters/webpack.config.js
raaghu-mfe/rds_pages/rds-page-pages/package.json
raaghu-mfe/rds_pages/rds-page-pages/webpack.config.js
raaghu-mfe/rds_pages/rds-page-polls/tsconfig.json
raaghu-mfe/rds_pages/rds-page-polls/webpack.config.js
raaghu-mfe/rds_pages/rds-page-register/package.json
raaghu-mfe/rds_pages/rds-page-register/webpack.config.js

Package names are changed, remove the babel warnings

---

raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx

changed the alignment of checkboxes.
Fixes #1774 

changed the alignment of checkboxes

---

raaghu-components/__tests__/rds-comp-card-detail-list.test.tsx

Created test script for Card detail list component 
Fixes #1762 

Created test script for Card detail list component 

---

raaghu-components/__tests__/rds-comp-benefit.test.tsx
raaghu-components/__tests__/rds-comp-contact-us.test.tsx
raaghu-components/__tests__/rds-comp-delivery-method.test.tsx
raaghu-components/__tests__/rds-comp-download-collation.test.tsx
raaghu-components/src/rds-comp-benefit/rds-comp-benefit.tsx
raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
raaghu-components/src/rds-comp-delivery-method/rds-comp-delivery-method.tsx
raaghu-components/src/rds-comp-download-collation/rds-comp-download-collation.tsx
raaghu-elements/src/rds-input/rds-input.tsx
raaghu-elements/src/rds-text-area/rds-text-area.tsx

Written test for benefit, contact us, delivery method and download collation
Fixes #1595

Written test for benefit, contact us, delivery method and download collation

---

raaghu-mfe/libs/state-management/personal-data/personal-data-slice.ts
raaghu-mfe/package.json
raaghu-mfe/rds_pages/rds-page-personaldata/src/personal-data/personal-data.tsx

>
> changes in personal-data
Fixes #1451 
- Test A
- Test B

changes in personal-data

---

raaghu-mfe/libs/state-management/Blogs/blogs-slice.ts
raaghu-mfe/libs/state-management/index.ts
raaghu-mfe/libs/state-management/public.api.ts
raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx

Data binding for blogs.
Fixes #1085 

data binding for blogs

---

raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx

Fixed issue in adding new blog.
Fixes #1786 

Fixed issue in adding new blog.

---

raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx

Enabled fields in edit offcanvas.
Fixes #1787 

Enabled fields in edit offcanvas.

---

raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx

Added delete functionality.
Fixes #1803 

Added delete functionality.

---

raaghu-components/__tests__/rds-comp-change-user-password.test.tsx

Created test script for Change user password component
Fixes #1762 

Created test script for Change user password component

---

package.json
raaghu-mfe/package.json
raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.stories.tsx

raaghu-themes version is incremented 0.0.32

---

raaghu-components/__tests__/rds-comp-calendar.test.tsx

Created test script for Calendar component
Fixes #1762 

Created test script for Calendar component

---

raaghu-components/src/rds-comp-register/rds-comp-register.tsx
raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
raaghu-mfe/rds_pages/rds-page-register/src/register/register.tsx

Fixes 
#1782 
#1753 
> Admin>>Edition>>Edit edition>>Features tab>>Restore, cancel and save button should be there.
> Functionality for registration page
- Test A
- Test B

PR for #1782 & #1753

---

raaghu-components/src/rds-comp-email/rds-comp-email.tsx
raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx
raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
> UI fixes in Users, settings 
Fixes #1692 #1785 
- Test A
- Test B

UI fixes in Users and Settings

---

raaghu-mfe/libs/state-management/Blogs/blogs-slice.ts

Did state management for blogs page.
Fixes #1808 

Did state management for blogs page.

---

raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx

Added Alert functionality in Blogs page
Fixes #1818  

Added Alert functionality in Blogs page

---

raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
>UI fixes in tenant and users
- Test A
- Test B

UI changes in tenant and user

---

raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx

Added Alert functionality in Payment Plan page
Fixes #1777 

Added Alert functionality in Payment Plan page

---

raaghu-components/__tests__/rds-comp-TenantManagement.test.tsx
raaghu-components/__tests__/rds-comp-app-detail.test.tsx
raaghu-components/__tests__/rds-comp-userbasics.test.tsx
raaghu-components/__tests__/rds-comp-userdelegation.test.tsx
raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
raaghu-components/src/rds-comp-tenant-management/rds-comp-tenant-management.tsx
raaghu-components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx
raaghu-components/src/rds-comp-user-permission-new/rds-comp-user-permission-new.tsx
raaghu-components/src/rds-comp-user-permission/rds-comp-user-permission.tsx
raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.tsx
raaghu-components/src/rds-comp-user-table/rds-comp-user-table.tsx
raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
raaghu-components/src/rds-comp-website-log/rds-comp-website-log.tsx

comitted  test casess

---

raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx

Fixed the issue in payment plan.
Fixes #1819 

Fixed the delete issue in payment plan.

---

raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx

Added hooks on the top in payment plans page
Added Alert functionality in Payment Plan page
Fixes #1777 

Added hooks on the top in payment plans page

---

package.json
raaghu-mfe/package.json

raaghu-themes version is incremented 0.0.33

---

raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx

Added Alert in file management.
Fixes #1806 

Added Alert in file management.

---

raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx

Added the file size limitation in file uploader
Fixes #1848 

Added the file size limitation in file uploader

---

raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx

Changed the limit type in file uploader
Fixes #1848 

changed the limit type in file uploader

---

raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx

Changed the limit type in file uploader.
Fixes #1830 

Added Validation for Profile picture.

---

raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx

Updated the UI of buttons in File management
Fixes #1861

Updated the UI of buttons in File management

---

raaghu-components/__tests__/rds-comp-themenew.test.tsx
raaghu-components/__tests__/rds-comp-userpermission.test.tsx
raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
raaghu-components/src/rds-comp-subscription/rds-comp-subscription.tsx
raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.tsx
raaghu-components/src/rds-comp-theme-new/rds-comp-theme-new.tsx
raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
raaghu-components/src/rds-comp-user-management/rds-comp-user-management.tsx
raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx

Comitted test cases for theme new, user permission

---

raaghu-components/__tests__/rds-comp-password-setting.test.tsx
raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx

added test for password-setting component
Fixes #1595 

added test for password-setting component

---

raaghu-components/__tests__/rds-comp-forms-basic.test.tsx
raaghu-components/__tests__/rds-comp-my-settings.test.tsx
raaghu-components/src/rds-comp-forms-basic/rds-comp-forms-basic.tsx

Added test for forms basic component.
Fixes #1595 

Added test for forms basic component.

---

raaghu-components/__tests__/rds-comp-forms-email.test.tsx
raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx

Added tests for form email component.
Fixes # 1595

Added tests for form email component.

---

raaghu-components/__tests__/rds-comp-forms-response.test.tsx

Added test file for forms response
Fixes # 1595

Added test file for forms response.

---

raaghu-components/__tests__/rds-comp-forms-setting.test.tsx
raaghu-components/src/rds-comp-forms-setting/rds-comp-forms-setting.tsx
raaghu-elements/src/rds-checkbox/rds-checkbox.tsx

Added test for forms setting.
Fixes #1595

Added test for forms setting.

---

raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx

Removed the the outdated breadcrumb in chats page.
Fixes #1881 

Removed the the outdated breadcrumb in chats page.

---

raaghu-components/__tests__/rds-comp-new-claim-type.test.tsx
raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx

added test file for new claim component
Fixes #1595 

added test file for new claim component

---

raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
raaghu-mfe/rds_pages/rds-page-myaccount/src/my-account/my-account.tsx
raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
> UI fixes done in different pages of raaghu-react
Fixes #1864  #1785 
- Test A
- …

UI bug fixes in language page, User Page

---

raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx

Added file validation for file uploader.
Fixes #1848 

Added file validation for file uploader.

---

raaghu-elements/src/rds-select-list/rds-select-list.tsx

Removed the chevron for multiple select list .
Fixes #1805 

Removed the chevron for multiple select list .

---

raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx

Fixed date range issue in audit log page.
Fixes #1834 

Fixed date range issue in audit log page.

---

raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx

Fixed issue in datepicker and audit logs page.
Fixes #1834 
- Test A
- Test B

Fixed issue in datepicker and audit logs page.

---

raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx

>
> language off canvas issue
- Test A
- Test B

new language off canvas issue

---

raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx

Removed console from audit log page. 
Fixes #1834 
- Test A
- Test B

Removed console from audit log page.

---

raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx

Added file upload validation in Profile picture component.
Fixes #1848 
- Test A
- Test B

Added file upload validation in Profile picture component.

---

raaghu-components/__tests__/rds-comp-personal-info.test.tsx
raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
raaghu-elements/src/rds-button/rds-button.tsx
raaghu-elements/src/rds-input/rds-input.tsx

Added test file for Personal Info component.
Fixes #1595 

Added test file for Personal Info component.

---

raaghu-components/__tests__/rds-comp-polls-option.test.tsx
raaghu-components/__tests__/rds-comp-polls-question.test.tsx
raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
raaghu-elements/src/rds-icon/rds-icon.tsx

Added test for polls option.
Fixes #1595

Added test for polls option.

---

raaghu-components/__tests__/rds-comp-profile-edit.test.tsx
raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx

Added test file for profile edit component
Fixes #1595 

Added test file for profile edit component

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
raaghu-elements/src/rds-button/rds-button.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
raaghu-mfe/libs/state-management/blog-post/blog-post-slice.ts
raaghu-mfe/package.json
raaghu-mfe/rds_pages/host/src/Main.tsx
raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx
raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/webhook/webhook.tsx

1. Fixed the backdrop issue.
2. Fixed the profile validation issue. 
Fixes #1830 #1781 

fixed the backdrop issue and save button issue.

---

raaghu-components/__tests__/rds-comp-forgot-password.test.tsx
raaghu-components/__tests__/rds-comp-icon-list.test.tsx
raaghu-components/__tests__/rds-comp-register.test.tsx
raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.tsx
raaghu-components/src/rds-comp-register/rds-comp-register.test.tsx
raaghu-components/src/rds-comp-register/rds-comp-register.tsx
raaghu-elements/src/rds-search/rds-search.tsx

Added test file for forgot-password, Icon list and register component.
Fixes #1595 

Added test file for forgot-password, Icon list and register component.

---

raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
raaghu-elements/src/rds-datepicker/rds-datepicker.tsx

Code enhanced in RdsDatePicker and comp-poll-question.tsx
Fixes #1816 

Code enhanced in RdsDatePicker and comp-poll-question.tsx

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-elements/src/rds-list-group/rds-list-group.tsx
raaghu-elements/src/rds-modal/rds-modal.css
raaghu-elements/src/rds-navbar/rds-navbar.css
raaghu-elements/src/rds-notification/rds-notification.css
raaghu-elements/src/rds-notification/rds-notification.tsx
raaghu-elements/src/rds-offcanvas/rds-offcanvas.css
raaghu-elements/src/rds-popular-page/rds-popular-page.css
raaghu-elements/src/rds-popular-page/rds-popular-page.tsx
raaghu-elements/src/rds-product-image/rds-product-image.tsx
raaghu-elements/src/rds-scrollspy/rds-scrollspy.tsx
raaghu-elements/src/rds-stepper/rds-stepper.tsx
raaghu-elements/src/rds-table/rds-table.tsx
raaghu-elements/src/rds-tag/rds-tag.css
raaghu-elements/src/rds-tag/rds-tag.tsx
raaghu-elements/src/rds-team-member/rds-team-member.css
raaghu-elements/src/rds-team-member/rds-team-member.stories.tsx
raaghu-elements/src/rds-team-member/rds-team-member.tsx
raaghu-elements/src/rds-testimonial/rds-testimonial.css
raaghu-elements/src/rds-text-editor/rds-text-editor.css
raaghu-elements/src/rds-tooltip/rds-tooltip.stories.tsx
raaghu-elements/src/rds-widget/rds-widget.tsx

Fixes
#1890 
#1900 
#1898 
#1527 
> UI - empty state illustration missing.
> Admin>>Pagination>>Spacing should be there between data table and pagination.
> Admin>>Pages>>4K>>Remove scrollbar.
> Include local SCSS and apply all themes from raaghu-themes package for all elements.
- Test A
- Test B

PR for #1900, #1898, #1890 & #1527

---

raaghu-components/__tests__/rds-comp-edit-language-text.test.tsx
raaghu-components/__tests__/rds-comp-identity-management-new.test.tsx
raaghu-components/src/rds-comp-edit-language-text/rds-comp-edit-language-text.tsx
raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx

Added test file for identity management and edit-language component.
Fixes #1595 

Added test file for identity management and edit-language component.

---

raaghu-components/__tests__/rds-comp-information.test.tsx
raaghu-components/__tests__/rds-comp-linked-account.test.tsx
raaghu-components/src/rds-comp-information/rds-comp-information.tsx
raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx

Added tests file for information and linked account component.
Fixes #1595

Added tests file for information and linked account component.

---

raaghu-components/__tests__/rds-comp-newPage.test.tsx
raaghu-components/__tests__/rds-comp-notification-settings.test.tsx
raaghu-components/src/rds-comp-newPage/rds-comp-newPage.tsx
raaghu-components/src/rds-comp-notification-settings/rds-comp-notification-settings.tsx

Added test file for newPage and notificatin settings component.
Fixes #1595 

Added test file for newPage and notificatin settings component.

---

raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
raaghu-mfe/rds_pages/host/src/Main.tsx

Fixed the language refresh bug 
Fixes #1542 

Fixed the language refresh bug

---

raaghu-components/__tests__/rds-comp-user-permission-new.test.tsx
raaghu-components/src/rds-comp-user-permission-new/rds-comp-user-permission-new.tsx

Added test file for user permission new component.
Fixes #1595

Added test file for user permission new component.

---

raaghu-mfe/libs/state-management/roles/roles-slice.ts
raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx

Resolved the Roles page bug while editing claims.
Fixes #1969 

Resolved the Roles page bug while editing claims.

---

raaghu-components/__tests__/rds-comp-login.test.tsx
raaghu-components/src/rds-comp-login/rds-comp-login.tsx

Added test file for login component.
Fixes #1595 

Added test file for login component.

---

raaghu-mfe/rds_pages/rds-page-pages/src/pages/pages.tsx

Fixed the bugs of data table grid in Pages.
Fixes #1983 

Fixed the bugs of data table grid in Pages

---

raaghu-components/__tests__/rds-comp-application-basic.test.tsx
raaghu-components/__tests__/rds-comp-properties.test.tsx
raaghu-components/jest.config.ts
raaghu-components/package.json

Added coverage report for raaghu-components. and added few more tests to application basic and properties component.
Fixes #2018

Added coverage report for raaghu-components. and added few more tests to application basic and properties component.

---

raaghu-mfe/rds_pages/host/src/Main.tsx

committed for set theme on refresh page

---

raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx

>
> Added core services on Tenant, User and Organization bug fixes
Fixes #2013 #1785 #1980  …

Organization unit, User and Tenant fixes

---

raaghu-mfe/libs/state-management/index.ts
raaghu-mfe/libs/state-management/logout/logout-slice.ts
raaghu-mfe/libs/state-management/public.api.ts
raaghu-mfe/rds_pages/host/src/Main.tsx

Login and logout issue#1373

---

raaghu-components/src/index.ts
raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
raaghu-components/src/rds-comp-application-scopes/index.ts
raaghu-components/src/rds-comp-application-scopes/rds-comp-application-scopes.stories.tsx
raaghu-components/src/rds-comp-application-scopes/rds-comp-application-scopes.styled.ts
raaghu-components/src/rds-comp-application-scopes/rds-comp-application-scopes.test.tsx
raaghu-components/src/rds-comp-application-scopes/rds-comp-application-scopes.tsx
raaghu-components/src/rds-comp-application-workflows/index.ts
raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.stories.tsx
raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.styled.ts
raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.test.tsx
raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
raaghu-mfe/rds_pages/rds-page-apiScope/src/apiScope/apiScope.tsx
raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
raaghu-mfe/rds_pages/rds-page-personaldata/src/personal-data/personal-data.tsx

Fixes
#1986 
#2014 
#2005 
> Admin>>OpenID>>Applications>>Update UI.
> Admin>>OpenID>>Scopes>>Edit>>Edit scopes title should be there.
> Admin>>Checkbox>>After clicking on text checkbox should gets selected.
- Test A
- Test B

PR for #1986 #2014  #2005 
